export const pageContentQuery = `*[_type == "pageContent"] | order(_updatedAt desc)[0]{
  _id,
  title,
  sections[]{
    _key,
    sectionType,
    enabled,
    showMore{
      enabled,
      text,
      linkType,
      internalPage,
      externalUrl
    },
    hero{
      badge,
      heading,
      description,
      primaryButton,
      primaryButtonUrl,
      secondaryButton,
      secondaryButtonUrl,
      showPrimaryButton,
      showSecondaryButton
    },
    stats[]{
      value,
      label,
      description
    },
    solutions[]{
      icon,
      title,
      description
    },
    community{
      heading,
      description,
      buttonText,
      buttonUrl,
      features[]{
        icon,
        title,
        description
      }
    },
    insights{
      heading,
      description,
      buttonText,
      buttonUrl
    },
    cta{
      heading,
      description,
      buttonText,
      buttonUrl,
      disclaimer
    },
    content{
      title,
      body,
      items,
      layout,
      image{
        asset->{
          _id,
          _type,
          url
        },
        hotspot,
        crop
      },
      imageAlt
    }
  }
}`

export const insightsQuery = `*[_type == "insight"] | order(publishedAt desc) {
  _id,
  title,
  slug,
  category,
  description,
  image,
  publishedAt,
  author
}[0...3]`

export const allInsightsQuery = `*[_type == "insight"] | order(publishedAt desc) {
  _id,
  title,
  slug,
  category,
  description,
  image,
  publishedAt,
  author
}`

export const insightBySlugQuery = `*[_type == "insight" && slug.current == $slug][0]{
  _id,
  title,
  slug,
  category,
  description,
  image,
  publishedAt,
  author,
  content
}`

export const featuredCommunityPostsQuery = `*[_type == "communityPost" && featured == true] | order(createdAt desc) [0...3]{
  _id,
  title,
  slug,
  author{
    name,
    avatar
  },
  replies,
  createdAt
}`

export const communityPostsQuery = `*[_type == "communityPost"] | order(createdAt desc) {
  _id,
  title,
  slug,
  author{
    name,
    avatar
  },
  content,
  replies,
  createdAt,
  featured
}`
